
server:
    port : 9001
spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/xuzhaokai/vessel-cloud.git     # ??git?????
                    search-paths: config-repo                             # git???????????????????,???
#                    username: root                                        # git?????
#                    password: password                                   # git?????
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8111/eureka/   ## ????eurka??